sudo: required
services:
    - docker
    
before_install:
    - docker build -t raks/docker-react -f Dockerfile.dev .
    
deploy:
    provider: elasticbeanstalk
    region: "us-east-1"
    app: "Docker"
    env: "Docker-env"
    bucket_name: "elasticbeanstalk-us-east-1-375311674115"
    bucket_path: "Docker"
    on:
        branch: master
