language: generic
sudo: required

services:
  - docker

before_install:
  - docker build -t Rakesh1788/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true Rakesh1788/docker-react npm run test